# Generated by Django 2.1.2 on 2022-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='qb_acc_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
