# Generated by Django 2.1.2 on 2022-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220725_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='qb_acc_id',
            new_name='qb_id',
        ),
        migrations.AddField(
            model_name='account',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Cost of Goods Sold', 'Cost of Goods Sold'), ('Sales of Product Income', 'Sales of Product Income')], default=None, max_length=30, null=True),
        ),
    ]
