# Generated by Django 2.1.2 on 2022-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220726_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, null=True)),
                ('value', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='synced',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
