# Generated by Django 2.1.2 on 2022-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220726_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('SalesOfProductIncome', 'Sales of Product Income'), ('CostOfLaborCos', 'Cost of Labor Cost')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Cost of Goods Sold', 'Cost of Goods Sold'), ('Income', 'Income')], default=None, max_length=30, null=True),
        ),
    ]
