# Generated by Django 2.2.9 on 2022-11-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220831_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='qbd_object_id',
            field=models.CharField(editable=False, max_length=127, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='qbd_object_updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='qbd_object_version',
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.AlterModelTable(
            name='currency',
            table='QBDModelMixin_qbdmodelmixin',
        ),
    ]
