# Generated by Django 2.1.2 on 2022-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Service', 'Service'), ('NonInventory', 'Non Inventory'), ('Inventory', 'Inventory'), ('Group', 'Group')], max_length=20)),
                ('qb_id', models.CharField(default=None, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
