# Generated by Django 2.2.9 on 2022-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='qb_id',
            new_name='grades',
        ),
        migrations.RemoveField(
            model_name='item',
            name='synced',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ocurrence',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='specific_terms',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
