# Generated by Django 2.2.9 on 2022-11-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20221119_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ocurrence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='period',
        ),
        migrations.RemoveField(
            model_name='item',
            name='specific_terms',
        ),
        migrations.RemoveField(
            model_name='item',
            name='term',
        ),
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
    ]
