# Generated by Django 2.1.2 on 2022-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=None, null=True),
        ),
    ]
