# Generated by Django 2.1.2 on 2022-08-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_remove_invoice_status'),
        ('payment', '0004_auto_20220729_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.Invoice'),
        ),
    ]
