# Generated by Django 2.1.2 on 2022-08-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_student_transport_fee'),
        ('payment', '0006_remove_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
        ),
    ]
