# Generated by Django 2.1.2 on 2022-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
