# Generated by Django 2.1.2 on 2022-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20220914_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
