# Generated by Django 4.1.1 on 2022-10-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_payment_invoice_alter_payment_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('can_view_summaries', 'can view payment summaries')]},
        ),
    ]
