# Generated by Django 4.1.1 on 2022-10-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('can_view_summaries', 'can view payment summaries'), ('can_add_fees_payments', 'Can add fees payments')]},
        ),
    ]
