# Generated by Django 2.2.9 on 2022-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bal_on_inv',
            field=models.IntegerField(null=True),
        ),
    ]
