# Generated by Django 2.2.9 on 2022-12-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_payment_bal_on_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bal_on_inv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='qb_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='synced',
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
