# Generated by Django 2.2.9 on 2022-12-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_overflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='note',
        ),
        migrations.AlterField(
            model_name='overflow',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
    ]
