# Generated by Django 2.2.9 on 2022-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20221202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
