# Generated by Django 2.2.9 on 2022-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20221213_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
