# Generated by Django 2.1.2 on 2022-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term_1_start_date', models.DateField()),
                ('term_1_end_date', models.DateField()),
                ('term_2_start_date', models.DateField()),
                ('term_2_end_date', models.DateField()),
                ('term_3_start_date', models.DateField()),
                ('term_3_end_date', models.DateField()),
            ],
        ),
    ]
