# Generated by Django 2.1.2 on 2022-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
