# Generated by Django 2.2.9 on 2022-12-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0004_auto_20221129_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='terms',
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Year'),
        ),
    ]
