# Generated by Django 2.2.9 on 2022-12-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0005_auto_20221201_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='code',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
    ]
