# Generated by Django 2.2.9 on 2022-12-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0006_auto_20221201_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='code',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='term',
            name='name',
        ),
    ]
