# Generated by Django 2.2.9 on 2022-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0008_auto_20221201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='start',
            field=models.DateField(),
        ),
    ]
