# Generated by Django 2.2.9 on 2022-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0009_auto_20221202_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
