# Generated by Django 2.2.9 on 2023-01-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0011_termnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_numbers', to='academic_calendar.TermNumbers'),
        ),
    ]
