# Generated by Django 2.1.2 on 2022-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
