# Generated by Django 2.1.2 on 2022-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20220701_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default=None, max_length=30, null=True, unique=True),
        ),
    ]
