# Generated by Django 2.1.2 on 2022-07-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20220701_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
    ]
