# Generated by Django 2.1.2 on 2022-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_billitem_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
