# Generated by Django 2.1.2 on 2022-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20220704_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='bill_number',
            field=models.CharField(default='<bill_number>', max_length=255),
            preserve_default=False,
        ),
    ]
