# Generated by Django 2.1.2 on 2022-07-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('bill', '0009_billitem_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.Vendor'),
        ),
    ]
