# Generated by Django 2.1.2 on 2022-07-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_remove_billitem_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('part-paid', 'part-paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=255),
        ),
    ]
