# Generated by Django 2.1.2 on 2022-09-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_billitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
