# Generated by Django 2.1.2 on 2022-09-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
