# Generated by Django 2.1.2 on 2022-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_auto_20220917_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='paid',
            new_name='fully_paid',
        ),
    ]
