# Generated by Django 4.1.1 on 2022-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_auto_20220920_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='price_per_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
