# Generated by Django 4.1.1 on 2022-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0020_alter_billitem_price_per_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(default=None, max_length=30, null=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
