# Generated by Django 4.1.1 on 2022-10-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'permissions': [('can_create_bill', 'can create a bill'), ('can_edit_bill', 'can edit the bill'), ('can_view_bill', 'can view the bill'), ('can_delete_bill', 'can delete the bill'), ('can_pay_bill', 'can pay the bill')]},
        ),
    ]
