# Generated by Django 4.1.1 on 2022-10-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0026_alter_billitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('vehicle_repair', 'Vehicle Repair'), ('office_supplies', 'Office Supplies'), ('educational resources', 'Educational Resources')], default=None, max_length=22, null=True),
        ),
    ]
