# Generated by Django 4.1.1 on 2022-10-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_billitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
