# Generated by Django 4.1.1 on 2022-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_alter_billitem_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='billitem',
            name='recipient',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='category',
            field=models.CharField(choices=[('office_supplies', 'Office Supplies'), ('teaching resources', 'Teaching Resources')], default=None, max_length=22, null=True),
        ),
    ]
