# Generated by Django 4.1.1 on 2022-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0029_remove_billitem_vendor_billitem_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
