# Generated by Django 4.1.1 on 2022-10-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0030_billitem_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='recipient',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
