# Generated by Django 4.1.1 on 2022-10-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_billitem_petty_cash_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
