# Generated by Django 4.1.1 on 2022-10-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0033_pettycash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='petty_cash_balance',
        ),
        migrations.AddField(
            model_name='billitem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='category',
            field=models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Teaching Reources', 'Teaching Resources'), ('Deposit', 'Deposit')], default=None, max_length=22, null=True),
        ),
    ]
