# Generated by Django 4.1.1 on 2022-10-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0034_remove_billitem_petty_cash_balance_billitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
