# Generated by Django 2.2.9 on 2022-12-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0037_alter_billitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='user',
        ),
    ]
