# Generated by Django 2.2.9 on 2022-12-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0041_billitem_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_day', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('billitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.BillItem')),
            ],
        ),
    ]
