# Generated by Django 2.2.9 on 2022-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0042_billpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='billitem',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
