# Generated by Django 2.2.9 on 2022-12-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0043_auto_20221221_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='balance',
            new_name='amount_due',
        ),
    ]
