# Generated by Django 2.2.26 on 2023-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0045_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=255)),
                ('amount', models.IntegerField()),
                ('day', models.DateField()),
            ],
        ),
    ]
