# Generated by Django 2.2.26 on 2023-01-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0046_cashtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='day',
            new_name='date',
        ),
    ]
