# Generated by Django 2.2.28 on 2022-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('petty cash', 'petty cash'), ('school transport', 'school transport'), ('electricity', 'electricity'), ('water', 'water'), ('payroll', 'payroll'), ('taxes', 'taxes'), ('other', 'other')], max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_per_quantity', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('synced', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('qb_id', models.CharField(default=None, max_length=255, null=True)),
                ('fully_paid', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_create_an_expense', 'can create an expense'), ('can_edit_an_expense', 'can edit and expense'), ('can_view_expenses', 'can view expenses'), ('can_delete_an_expense', 'can discard and expense'), ('can_confirm_add_an_expense', 'can confirm add and expense'), ('can_view_summaries', 'can view summaries')],
            },
        ),
    ]
