# Generated by Django 2.1.2 on 2022-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
