# Generated by Django 2.2.9 on 2022-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_code',
            field=models.IntegerField(null=True),
        ),
    ]
