# Generated by Django 2.1.2 on 2022-07-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20220701_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='bill_number',
            new_name='bill',
        ),
    ]
