# Generated by Django 2.1.2 on 2022-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_billitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='qb_bill_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
