# Generated by Django 2.1.2 on 2022-07-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_billitem_qb_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='qb_bill_id',
            new_name='qb_id',
        ),
    ]
