# Generated by Django 2.1.2 on 2022-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_auto_20220726_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill_number',
        ),
    ]
