# Generated by Django 2.1.2 on 2022-09-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_auto_20220917_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='status',
        ),
        migrations.AddField(
            model_name='billitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
