# Generated by Django 2.1.2 on 2022-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0018_auto_20220917_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='price_per_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='total',
            field=models.IntegerField(),
        ),
    ]
