# Generated by Django 4.1.1 on 2022-10-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0023_alter_bill_options_alter_billitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={'permissions': [('can_create_bill', 'can create the bill'), ('can_edit_bill', 'can edit the bill'), ('can_view_bill', 'can view the bill'), ('can_delete_bill', 'can delete the bill'), ('can_pay_bill', 'can pay the bill')]},
        ),
    ]
