# Generated by Django 2.2.9 on 2022-10-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QBWEBSERVICE', '0004_auto_20200122_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realmsession',
            name='realm',
        ),
        migrations.AlterModelTable(
            name='realm',
            table='Realm_realm',
        ),
        migrations.DeleteModel(
            name='QBDTask',
        ),
        migrations.DeleteModel(
            name='RealmSession',
        ),
    ]
