# Generated by Django 2.2.9 on 2022-10-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('QBWEBSERVICE', '0005_auto_20221027_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealmSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='Ticket for QBWC session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='QBWEBSERVICE.Realm')),
            ],
            options={
                'db_table': 'RealmSession_realmsession',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QBDTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qb_operation', models.CharField(max_length=25)),
                ('qb_resource', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_tasks', to='QBWEBSERVICE.Realm')),
            ],
            options={
                'db_table': 'QBDTask_qbdtask',
                'abstract': False,
            },
        ),
    ]
