# Generated by Django 2.1.2 on 2022-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
