# Generated by Django 2.1.2 on 2022-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20220709_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.TextField(default=None, null=True),
        ),
    ]
