# Generated by Django 2.2.9 on 2022-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_auto_20221027_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
