# Generated by Django 2.1.2 on 2022-08-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0002_vendor_qb_vendor_id'),
        ('bill', '0014_billitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('synced', models.BooleanField(default=None, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.Bill')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.Vendor')),
            ],
        ),
    ]
