# Generated by Django 2.1.2 on 2022-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payment', '0002_auto_20220829_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
