# Generated by Django 4.1.1 on 2022-10-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payment', '0003_billpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='vendor',
        ),
    ]
