# Generated by Django 2.1.2 on 2022-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default=None, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport_fee',
            field=models.IntegerField(default=0),
        ),
    ]
