# Generated by Django 2.1.2 on 2022-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220630_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
