# Generated by Django 2.1.2 on 2022-06-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
    ]
