# Generated by Django 2.1.2 on 2022-06-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220630_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
    ]
