# Generated by Django 2.1.2 on 2022-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20220707_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number_formatted',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
