# Generated by Django 2.1.2 on 2022-07-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_admission_number_formatted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='hot_lunch',
            new_name='lunch',
        ),
    ]
