# Generated by Django 2.1.2 on 2022-07-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20220712_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_of_admission']},
        ),
    ]
