# Generated by Django 2.1.2 on 2022-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20220712_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qb_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(),
        ),
    ]
