# Generated by Django 2.1.2 on 2022-07-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20220726_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='transport_fee',
        ),
    ]
