# Generated by Django 2.1.2 on 2022-09-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_student_transport_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
