# Generated by Django 2.2.9 on 2022-11-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20221029_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
