# Generated by Django 2.2.9 on 2022-12-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20221202_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qbd_object_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qbd_object_updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qbd_object_version',
        ),
    ]
