# Generated by Django 2.2.9 on 2022-12-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0008_auto_20221201_1725'),
        ('student', '0022_auto_20221202_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_term', to='academic_calendar.Term'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_year', to='academic_calendar.Year'),
        ),
    ]
