# Generated by Django 2.2.9 on 2022-12-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20221203_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='primary_contact_name',
            new_name='contact1_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='primary_contact_phone_number',
            new_name='contact1_phone_number',
        ),
    ]
