# Generated by Django 2.1.2 on 2022-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tuition', models.IntegerField()),
                ('lunch', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('admission', models.IntegerField()),
                ('diary_and_report_book', models.IntegerField()),
                ('interview', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Grade')),
            ],
        ),
    ]
