# Generated by Django 2.1.2 on 2022-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='term',
            field=models.IntegerField(choices=[('1st Term', 1), ('2nd Term', 2), ('3rd Term', 3)]),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='year',
            field=models.IntegerField(choices=[('...', 0), ('2020', 2020), ('2021', 2021), ('2022', 2022), ('...', 1)]),
        ),
    ]
