# Generated by Django 2.1.2 on 2022-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0002_auto_20220704_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='term',
            field=models.IntegerField(choices=[(1, '1st Term'), (2, '2nd Term'), (3, '3rd Term')]),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='year',
            field=models.IntegerField(choices=[(0, '...'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (1, '...')]),
        ),
    ]
