# Generated by Django 2.1.2 on 2022-07-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0003_auto_20220705_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='year',
        ),
    ]
