# Generated by Django 2.1.2 on 2022-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0004_remove_feesstructure_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesstructure',
            old_name='computer',
            new_name='computer_lessons',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='diary_and_report_book',
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='diary',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='report_book',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
