# Generated by Django 2.2.28 on 2022-10-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0006_auto_20220726_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesstructure',
            options={'permissions': [('can_edit_the_fees_structure', 'can edit the fees structure'), ('can_view_the_fees_structure', 'can view the fees structure')]},
        ),
    ]
