# Generated by Django 2.2.9 on 2022-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0007_auto_20221021_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesstructure',
            options={'permissions': [('can_create_a_fees_structure', 'can edit the fees structure'), ('can_view_the_fees_structure', 'can view the fees structure')]},
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='grades',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='specific_terms',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='year_round',
            field=models.BooleanField(default=False),
        ),
    ]
