# Generated by Django 2.2.9 on 2022-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0008_auto_20221110_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='one_time',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='recurring',
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='ocurrence',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
