# Generated by Django 2.2.9 on 2022-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0009_auto_20221116_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='year_round',
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='period',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
