# Generated by Django 2.2.9 on 2022-11-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0010_auto_20221119_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesstructure',
            options={},
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
