# Generated by Django 2.2.9 on 2022-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0011_auto_20221120_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='charge_on_registration',
            field=models.BooleanField(default=False),
        ),
    ]
