# Generated by Django 2.2.9 on 2022-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0012_feesstructure_charge_on_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='charge_on_registration',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='ocurrence',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='period',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='specific_terms',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
