# Generated by Django 2.2.9 on 2022-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0014_auto_20221125_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructureBatchNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
