# Generated by Django 2.2.9 on 2022-11-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20221120_0656'),
        ('fees_structure', '0016_feesstructure_fee_structure_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructurebatchnumber',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatchnumber',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
