# Generated by Django 2.2.9 on 2022-11-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20221120_0656'),
        ('fees_structure', '0017_auto_20221125_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeesStructureBatchNumber',
            new_name='FeesStructureBatch',
        ),
    ]
