# Generated by Django 2.2.9 on 2022-11-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_structure', '0018_auto_20221125_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructurebatch',
            name='charge_on_registration',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='grades',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='last_modified_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='ocurrence',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='period',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='specific_terms',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
