# Generated by Django 2.2.9 on 2022-11-26 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_grade_grade_code'),
        ('academic_calendar', '0003_term_year'),
        ('fees_structure', '0019_auto_20221125_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='charge_on_registration',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='created',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='fee_structure_batch_number',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='item',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='ocurrence',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='period',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='specific_terms',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='year',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='specific_terms',
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='terms',
            field=models.ManyToManyField(null=True, to='academic_calendar.Term'),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='grades',
        ),
        migrations.AddField(
            model_name='feesstructurebatch',
            name='grades',
            field=models.ManyToManyField(null=True, to='grade.Grade'),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='last_modified_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='ocurrence',
            field=models.CharField(choices=[('recurring', 'recurring'), ('one-time', 'one-time')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic_calendar.Term'),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Year'),
        ),
    ]
