# Generated by Django 2.2.9 on 2022-11-26 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0021_auto_20221126_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='charge_on_registration',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic_calendar.Term'),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='terms',
            field=models.ManyToManyField(blank=True, to='academic_calendar.Term'),
        ),
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Year'),
        ),
    ]
