# Generated by Django 2.2.9 on 2022-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0022_auto_20221126_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='period',
            field=models.CharField(blank=True, choices=[('year-round', 'year-round'), ('specific-terms', 'specific-terms')], default=None, max_length=50, null=True),
        ),
    ]
