# Generated by Django 2.2.9 on 2022-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0023_auto_20221129_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructurebatch',
            name='ocurrence',
            field=models.CharField(choices=[('recurring', 'recurring'), ('one-time', 'one-time'), ('optional', 'optional')], default=None, max_length=30, null=True),
        ),
    ]
