# Generated by Django 2.2.9 on 2022-12-11 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0010_auto_20221206_1048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grade', '0003_grade_grade_code'),
        ('item', '0004_auto_20221206_1048'),
        ('fees_structure', '0024_auto_20221203_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='charge_on_registration',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='created',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='item',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='ocurrence',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='period',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='feesstructurebatch',
            name='year',
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=None, null=True)),
                ('ocurrence', models.CharField(choices=[('recurring', 'recurring'), ('one-time', 'one-time'), ('optional', 'optional')], default=None, max_length=30, null=True)),
                ('period', models.CharField(blank=True, choices=[('year-round', 'year-round'), ('specific-terms', 'specific-terms')], default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('charge_on_registration', models.BooleanField(blank=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(to='grade.Grade')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('last_modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic_calendar.Term')),
                ('terms', models.ManyToManyField(blank=True, to='academic_calendar.Term')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Year')),
            ],
        ),
    ]
