# Generated by Django 2.2.26 on 2023-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0026_auto_20230102_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='ocurrence',
            field=models.CharField(choices=[('recurring', 'recurring'), ('one-time', 'one-time'), ('optional', 'optional'), ('registration', 'registration')], default=None, max_length=30, null=True),
        ),
    ]
