# Generated by Django 2.2.26 on 2023-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0027_auto_20230119_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='grades',
            field=models.ManyToManyField(null=True, to='grade.Grade'),
        ),
    ]
