# Generated by Django 2.2.26 on 2023-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0028_auto_20230120_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='visibe',
            field=models.BooleanField(default=True),
        ),
    ]
