# Generated by Django 2.2.26 on 2023-01-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0029_billingitem_visibe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingitem',
            old_name='visibe',
            new_name='visible',
        ),
    ]
