# Generated by Django 2.1.2 on 2022-07-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('student', '0005_auto_20220630_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('part-paid', 'part-paid'), ('unpaid', 'unpaid')], max_length=255)),
                ('invoice_number', models.CharField(default=None, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade.Grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('admission', 'admission'), ('diary_and_report_book', 'diary_and_report_book'), ('interview_fee_lower_classes', 'interview_fee_lower_classes'), ('interview_fee_upper_classes', 'interview_fee_upper_classes'), ('tuition', 'tuition'), ('computer_lessons', 'computer_lessons'), ('transport', 'transport'), ('lunch', 'lunch')], max_length=255)),
                ('amount', models.IntegerField()),
                ('synced', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
