# Generated by Django 2.1.2 on 2022-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('part-paid', 'part-paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=255),
        ),
    ]
