# Generated by Django 2.1.2 on 2022-07-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20220705_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_description',
        ),
    ]
