# Generated by Django 2.1.2 on 2022-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20220707_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number_formatted',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
