# Generated by Django 2.1.2 on 2022-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(choices=[('admission', 'admission'), ('diary_and_report_book', 'diary_and_report_book'), ('interview_fee_lower_classes', 'interview_fee_lower_classes'), ('interview_fee_upper_classes', 'interview_fee_upper_classes'), ('tuition', 'tuition'), ('computer_lessons', 'computer_lessons'), ('transport', 'transport'), ('lunch', 'lunch')], default=None, max_length=255, null=True),
        ),
    ]
