# Generated by Django 2.1.2 on 2022-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_balancetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetable',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='balancetable',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', unique=True),
        ),
    ]
