# Generated by Django 2.1.2 on 2022-07-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20220712_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetable',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
