# Generated by Django 2.1.2 on 2022-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_item_qb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
