# Generated by Django 2.1.2 on 2022-07-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoice_qb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='grade',
        ),
    ]
