# Generated by Django 2.1.2 on 2022-07-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_invoice_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='term',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='year',
        ),
    ]
