# Generated by Django 2.1.2 on 2022-07-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20220727_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qb_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='synced',
        ),
    ]
