# Generated by Django 2.1.2 on 2022-08-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20220728_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
