# Generated by Django 2.1.2 on 2022-08-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('invoice', '0017_auto_20220824_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='sales_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.Item'),
        ),
    ]
