# Generated by Django 2.1.2 on 2022-08-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20220824_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sales_item',
            new_name='invoice_item',
        ),
    ]
