# Generated by Django 2.1.2 on 2022-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_auto_20220824_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
