# Generated by Django 2.1.2 on 2022-08-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20220824_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
