# Generated by Django 2.1.2 on 2022-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_remove_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
