# Generated by Django 2.1.2 on 2022-08-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_auto_20220831_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='paid',
        ),
    ]
