# Generated by Django 2.1.2 on 2022-09-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_invoice_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid',
            new_name='paid_status',
        ),
    ]
