# Generated by Django 2.1.2 on 2022-09-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_auto_20220913_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number_formatted',
        ),
    ]
