# Generated by Django 2.1.2 on 2022-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_auto_20220913_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid_status',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
