# Generated by Django 2.1.2 on 2022-09-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_grade_number'),
        ('invoice', '0030_auto_20220913_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grade.Grade'),
        ),
    ]
