# Generated by Django 2.1.2 on 2022-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_invoice_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
