# Generated by Django 2.2.9 on 2022-10-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_auto_20220916_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qbd_object_id',
            field=models.CharField(editable=False, max_length=127, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qbd_object_updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qbd_object_version',
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='QBDModelMixin_qbdmodelmixin',
        ),
    ]
