# Generated by Django 2.2.9 on 2022-10-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_auto_20221029_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qb_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='synced',
        ),
    ]
