# Generated by Django 2.2.9 on 2022-10-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_auto_20221029_0851'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='Invoice_invoice',
        ),
    ]
