# Generated by Django 2.2.9 on 2022-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_invoice_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qbd_object_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='qbd_object_updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='qbd_object_version',
        ),
    ]
