# Generated by Django 2.2.9 on 2022-12-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0037_auto_20221202_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid',
            new_name='fully_paid',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Term'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_calendar.Year'),
        ),
    ]
