# Generated by Django 2.2.9 on 2022-12-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0038_auto_20221202_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='invoice_item',
            new_name='sales_item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
