# Generated by Django 2.2.9 on 2022-12-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_auto_20221202_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fully_paid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
    ]
