# Generated by Django 2.2.9 on 2022-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0040_auto_20221202_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
