# Generated by Django 2.2.9 on 2022-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0041_invoice_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
