# Generated by Django 2.2.9 on 2022-12-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0025_auto_20221211_0544'),
        ('invoice', '0043_auto_20221214_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sales_item',
        ),
        migrations.AddField(
            model_name='item',
            name='billing_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='fees_structure.BillingItem'),
        ),
    ]
