# Generated by Django 2.2.9 on 2022-12-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0044_auto_20221215_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='billing_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='fees_structure.BillingItem'),
        ),
    ]
