# Generated by Django 2.2.9 on 2022-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0045_auto_20221215_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'get_latest_by': 'created_sys'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_sys',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
